version: '3.9'
services:
  mariadb:
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - ~/maria_db:/var/lib/mysql
      - ./resources/init/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=cc_user
      - MYSQL_DATABASE=community_cupboard
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    image: 'web'
    container_name: web
    ports:
      - '80:5000'
    environment:
      - FLASK_ENV=dev
      - FLASK_DEBUG=1
      - SECRET_KEY=\x02"c\xc9\xf3\x82\xd8\xde\xaf\x9cB\xc6\xd3\x0f\x9a)u\x9a\x85\xb6\xf5\x8f\x80j
    links:
      - mariadb