version: '3.9'
services:
  mariadb:
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=citizix_user
      - MYSQL_DATABASE=citizix_db
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    image: 'web'
    container_name: web
    ports:
      - '80:5000'
    environment:
      - FLASK_ENV=dev
      - FLASK_DEBUG=1
      - TASK_QUE_SERVER_REDIS=redis
      - SECRET_KEY=\x02"c\xc9\xf3\x82\xd8\xde\xaf\x9cB\xc6\xd3\x0f\x9a)u\x9a\x85\xb6\xf5\x8f\x80j
      - DB_HOST=
      - DB_USER=
      - DB_PASSWORD=
      - DB_DRIVER=mysql+mysqlconnector
      - DB_PORT=3306
      - DB_NAME=
    links:
      - mariadb